"""
NR426 Lab3A
Completed by: Zachary Cramton
Date: 17FEB2026

Submitted with Lab 4B demo deliverable (.png) as instructed.

This lab practices the basics of using select tools and accessing tables. It saves the report to a text file for easy
viewing. To change the text file name or destination check
"""
# Import Modules
import arcpy
import os
import sys
import datetime # Added for dating of text report

# Workspace Setup
dataLoc = r"L4LabData\RoadkillDataLab4.gdb"

# Check if the folder exists before asking for a filename
if not arcpy.Exists(dataLoc):
    print (f"The workspace does not exist at {dataLoc}. Check your path.")
    sys.exit()

# Feature Class Names
roadkill = "RoadkillSightings_UTM"
counties = "HRVCounties"
roads = "HRVRoads"

# ----- Extra (6) Report Setup -----
# Define report name, time, and destination
reportName = "CramtonZ_NR426_Lab4B_Report.txt"
reportPath = os.path.join(os.path.dirname(dataLoc), reportName)
timestamp = datetime.datetime.now().strftime("%d%b%Y %H:%M:%S").upper()

# Update user on progress
print ("Generating Report...")

# Try except error handleing
try:
    # Open the file and start the process
    with open (reportPath, 'w') as f:
        # Report header (Printing to file=f)
        print (f"{'=' * 60}", file=f)
        print (f"NR426 L4b: Selection report", file=f)
        print (f"Generated on: {timestamp}", file=f)
        print (f"Generated by: {os.getenv("USERNAME")}", file=f)
        print (f"{'=' * 60}\n", file=f)

        # +++++ Base Assignment Activities +++++
        # ----- 1) EAH Solo Collection Points -----
        # Define query to find observations made by EAH alone.
        arcpy.management.SelectLayerByAttribute(
            in_layer_or_view = roadkill,
            select_geometry = "",
            where_clause = "Observer = 'EAH'"
        )
        count1 = arcpy.management.GetCount(roadkill)[0]
        print (f"1. EAH Solo Observations: {count1}\n", file=f)


        # ----- 2) EAH Total Collection Points -----
        # Use LIKE with % wildcard to find all observations where EAH was present
        arcpy.management.SelectLayerByAttribute(
            in_layer_or_view = roadkill,
            select_geometry = "",
            where_clause = "Observer LIKE '%EAH%'"
        )
        count2 = arcpy.management.GetCount(roadkill)[0]
        print (f"2. EAH Total Observations: {count2}\n", file=f)


        # ----- 3) Create New FC With All Points In Ulster Co -----
        # Select the county
        # ulsterCO = arcpy.management.MakeFeatureLayer(
        #     in_features = counties,
        #     out_layer= "ulster_county",
        #     "ulster)
        # arcpy.management.SelectLayerByAttribute()



        # ----- 4) Buffer Striped Skunks in Ulster Co by 0.25 Miles -----




        # ----- 5) Buffer Roads 200ft; Check for Points NOT in Buffer

except arcpy.ExecuteError:
    print (arcpy.GetMessages(2))

except Exception as e:
    print (f"An error occurred: {e}")


