"""
NR426 Lab3A
Completed by: Zachary Cramton
Date: 17FEB2026

Submitted with Lab 4B demo deliverable (.png) as instructed.

This lab practices the basics of using select tools and accessing tables. It saves the report to a text file for easy
viewing. To change the text file name or destination check
"""
# Import Modules
import arcpy
import os
import sys
import datetime # Added for dating of text report

# Workspace Setup
dataLoc = r"L4LabData\RoadkillDataLab4.gdb"

# Check if the folder exists before asking for a filename
if not arcpy.Exists(dataLoc):
    print(f"The workspace does not exist at {dataLoc}. Check your path.")
    sys.exit()

# ----- Extra (6) Report Setup -----
# Define report name, time, and destination
reportName = "CramtonZ_NR426_Lab4B_Report"
reportPath = r"..\{dataLoc}"
timestamp = datetime.datetime.now().strftime("%d%b%Y %H:%M:%S").upper()

# Update user on progress
print ("Generating Report...")

# Open the file and start the process
with open(reportPath, 'w') as f:
    # Header logic (Printing to file=f)
    print(f"{'=' * 60}", file=f)
    print(f"NR426 L4b: Selection report", file=f)
    print(f"Generated on: {timestamp}", file=f)
    print(f"generated by: {os.getenv("USERNAME")}, file=f)
    print(f"{'=' * 60}\n", file=f)

    # +++++ Base Assignment Activities +++++
    # ----- 1) EAH Solo Collection Points -----
    query =
    arcpy.management.SelectLayerByAttribute(
        in_layer_or_view=roadkill,
        select_geometry="",
        where_clause= query,
        invert_where_clause="INVERT"
    )


    # ----- 2) EAH Total Collection Points -----
    # use a wildcard


    # ----- 3) Create New FC With All Points In Ulster Co -----




    # ----- 4) Buffer Striped Skunks in Ulster Co by 0.25 Miles -----




    # ----- 5) Buffer Roads 200ft; Check for Points NOT in Buffer


